name: dart_nbt
description: A Dart library for reading and writing Minecraft NBT (Named Binary Tag) data.
version: 0.1.2
repository: https://github.com/Frogperson/dart_nbt

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  typed_data: ^1.4.0
  archive: ^4.0.7
  buffer: ^1.2.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  path: ^1.9.1
